<a href="https://colab.research.google.com/github/ju-log/Memory/blob/Momentum-3rd-project/EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone -b Momentum-3rd-project https://github.com/ju-log/Memory.git

In [17]:
import numpy as np
import pandas as pd

**Price. 비급여_MRI_체외충격파_가격**

In [18]:
price = pd.read_csv("/content/Memory/서울_비급여_MRI_체외충격파 (4).csv")

hospital = pd.read_excel("/content/Memory/병원정보서비스(2026.6)_서울_병원_종합병원_상급종합 (1).xlsx")

facility = pd.read_excel("/content/Memory/의료기관별상세정보서비스_01_시설정보(2026.6)_서울_병원_종합병원_상급종합.xlsx")

dept = pd.read_excel("/content/Memory/의료기관별상세정보서비스_03_진료과목정보(2026.6)_서울_병원_종합병원_상급종합.xlsx")

traffic = pd.read_excel("/content/Memory/의료기관별상세정보서비스_04_교통정보_서울_병원_종합병원_상급종합.xlsx")

In [19]:
# 행렬 확인
price.shape

(435, 15)

In [20]:
# 열이름 확인
price.columns

Index(['analysisItem', 'ykiho', 'yadmNm', 'clCd', 'clCdNm', 'sidoCdNm',
       'sgguCdNm', 'npayCd', 'npayKorNm', 'npayDtlDivCd', 'npayDtlDivCdNm',
       'adtFrDd', 'adtEndDd', 'minPrc', 'maxPrc'],
      dtype='object')

In [21]:
# 값 확인
price.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   analysisItem    435 non-null    object
 1   ykiho           435 non-null    object
 2   yadmNm          435 non-null    object
 3   clCd            435 non-null    int64
 4   clCdNm          435 non-null    object
 5   sidoCdNm        435 non-null    object
 6   sgguCdNm        435 non-null    object
 7   npayCd          435 non-null    object
 8   npayKorNm       435 non-null    object
 9   npayDtlDivCd    435 non-null    object
 10  npayDtlDivCdNm  435 non-null    object
 11  adtFrDd         435 non-null    int64
 12  adtEndDd        435 non-null    int64
 13  minPrc          435 non-null    int64
 14  maxPrc          435 non-null    int64
dtypes: int64(5), object(10)
memory usage: 51.1+ KB

In [22]:
# NULL 확인
price.isnull().sum()

analysisItem      0
ykiho             0
yadmNm            0
clCd              0
clCdNm            0
sidoCdNm          0
sgguCdNm          0
npayCd            0
npayKorNm         0
npayDtlDivCd      0
npayDtlDivCdNm    0
adtFrDd           0
adtEndDd          0
minPrc            0
maxPrc            0
dtype: int64

In [23]:
# 중복 확인
price.duplicated().sum()

np.int64(0)

In [28]:
# 항목당 비급여 수 확인
price["analysisItem"].value_counts()

analysisItem
체외충격파치료     266
MRI_뇌_일반    169
Name: count, dtype: int64

In [29]:
price.groupby("analysisItem")["ykiho"].nunique()

analysisItem
MRI_뇌_일반    169
체외충격파치료     266
Name: ykiho, dtype: int64

In [32]:
# 가격 분포 확인
price.groupby("analysisItem")[["minPrc","maxPrc"]].describe()

             minPrc                                                    \
              count           mean            std       min       25%
analysisItem
MRI_뇌_일반      169.0  515727.159763  144089.557944  250000.0  430000.0
체외충격파치료       266.0   67658.909774   29540.326833   10000.0   50000.0

                                            maxPrc                 \
                   50%       75%        max  count           mean
analysisItem
MRI_뇌_일반      490000.0  564200.0  1045000.0  169.0  535095.207101
체외충격파치료        60000.0   80000.0   201000.0  266.0  136725.526316


                        std       min       25%       50%       75%        max
analysisItem
MRI_뇌_일반      155431.553375  250000.0  450000.0  499000.0  600000.0  1045000.0
체외충격파치료        65298.895595   22000.0   81445.0  130000.0  170000.0   354000.0

In [34]:
# 가격 차이 여부 확인
(price["minPrc"] != price["maxPrc"]).sum()

np.int64(224)

**Hospital. 병원_기본_정보**

In [35]:
hospital.shape

(290, 30)

In [36]:
hospital.columns

Index(['암호화요양기호', '요양기관명', '종별코드', '종별코드명', '시도코드', '시도코드명', '시군구코드', '시군구코드명',
       '읍면동', '우편번호', '주소', '전화번호', '병원홈페이지', '개설일자', '총의사수', '의과일반의 인원수',
       '의과인턴 인원수', '의과레지던트 인원수', '의과전문의 인원수', '치과일반의 인원수', '치과인턴 인원수',
       '치과레지던트 인원수', '치과전문의 인원수', '한방일반의 인원수', '한방인턴 인원수', '한방레지던트 인원수',
       '한방전문의 인원수', '조산사 인원수', '좌표(X)', '좌표(Y)'],
      dtype='object')

In [37]:
hospital.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 290 entries, 0 to 289
Data columns (total 30 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   암호화요양기호     290 non-null    object
 1   요양기관명       290 non-null    object
 2   종별코드        290 non-null    int64
 3   종별코드명       290 non-null    object
 4   시도코드        290 non-null    int64
 5   시도코드명       290 non-null    object
 6   시군구코드       290 non-null    int64
 7   시군구코드명      290 non-null    object
 8   읍면동         290 non-null    object
 9   우편번호        290 non-null    int64
 10  주소          290 non-null    object
 11  전화번호        290 non-null    object
 12  병원홈페이지      156 non-null    object
 13  개설일자        290 non-null    datetime64[ns]
 14  총의사수        290 non-null    int64
 15  의과일반의 인원수   290 non-null    int64
 16  의과인턴 인원수    290 non-null    int64
 17  의과레지던트 인원수  290 non-null    int64
 18  의과전문의 인원수   290 non-null    int64
 19  치과일반의 인원수   290 non-null    int64
 20  치과인턴 인원수    290 non-null    int64
 21  치과레지던트 인원수  290 non-null    int64
 22  치과전문의 인원수   290 non-null    int64
 23  한방일반의 인원수   290 non-null    int64
 24  한방인턴 인원수    290 non-null    int64
 25  한방레지던트 인원수  290 non-null    int64
 26  한방전문의 인원수   290 non-null    int64
 27  조산사 인원수     290 non-null    int64
 28  좌표(X)       290 non-null    float64
 29  좌표(Y)       290 non-null    float64
dtypes: datetime64[ns](1), float64(2), int64(18), object(9)
memory usage: 68.1+ KB

In [38]:
hospital.isnull().sum()

암호화요양기호         0
요양기관명           0
종별코드            0
종별코드명           0
시도코드            0
시도코드명           0
시군구코드           0
시군구코드명          0
읍면동             0
우편번호            0
주소              0
전화번호            0
병원홈페이지        134
개설일자            0
총의사수            0
의과일반의 인원수       0
의과인턴 인원수        0
의과레지던트 인원수      0
의과전문의 인원수       0
치과일반의 인원수       0
치과인턴 인원수        0
치과레지던트 인원수      0
치과전문의 인원수       0
한방일반의 인원수       0
한방인턴 인원수        0
한방레지던트 인원수      0
한방전문의 인원수       0
조산사 인원수         0
좌표(X)           0
좌표(Y)           0
dtype: int64

In [39]:
hospital.duplicated().sum()

np.int64(0)

In [41]:
# 구별 병원 수
hospital["시군구코드명"].value_counts()

시군구코드명
강남구     36
송파구     24
강서구     24
강동구     20
영등포구    16
중랑구     16
동대문구    16
서초구     16
은평구     13
관악구     12
구로구     12
강북구     10
노원구      8
양천구      7
성북구      7
종로구      7
동작구      7
마포구      6
성동구      6
광진구      6
금천구      6
도봉구      5
서대문구     4
중구       4
용산구      2
Name: count, dtype: int64

**Facility.병원_시설_정보**

In [42]:
facility.shape

(290, 30)

In [43]:
facility.columns

Index(['암호화요양기호', '요양기관명', '종별코드', '종별코드명', '설립구분코드', '설립구분코드명', '시도코드',
       '시도코드명', '시군구코드', '시군구코드명', '읍면동', '우편번호', '주소', '전화번호', '개설일자',
       '일반입원실상급병상수', '일반입원실일반병상수', '성인중환자병상수', '소아중환자병상수', '신생아중환자병상수',
       '분만실병상수', '수술실병상수', '응급실병상수', '물리치료실병상수', '정신과폐쇄상급병상수', '정신과폐쇄일반병상수',
       '정신과개방상급병상수', '정신과개방일반병상수', '격리병실병상수', '무균치료실병상수'],
      dtype='object')

In [44]:
facility.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 290 entries, 0 to 289
Data columns (total 30 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   암호화요양기호     290 non-null    object
 1   요양기관명       290 non-null    object
 2   종별코드        290 non-null    int64
 3   종별코드명       290 non-null    object
 4   설립구분코드      290 non-null    int64
 5   설립구분코드명     290 non-null    object
 6   시도코드        290 non-null    int64
 7   시도코드명       290 non-null    object
 8   시군구코드       290 non-null    int64
 9   시군구코드명      290 non-null    object
 10  읍면동         290 non-null    object
 11  우편번호        290 non-null    int64
 12  주소          290 non-null    object
 13  전화번호        290 non-null    object
 14  개설일자        290 non-null    datetime64[ns]
 15  일반입원실상급병상수  290 non-null    int64
 16  일반입원실일반병상수  290 non-null    int64
 17  성인중환자병상수    290 non-null    int64
 18  소아중환자병상수    290 non-null    int64
 19  신생아중환자병상수   290 non-null    int64
 20  분만실병상수      290 non-null    int64
 21  수술실병상수      290 non-null    int64
 22  응급실병상수      290 non-null    int64
 23  물리치료실병상수    290 non-null    int64
 24  정신과폐쇄상급병상수  290 non-null    int64
 25  정신과폐쇄일반병상수  290 non-null    int64
 26  정신과개방상급병상수  290 non-null    int64
 27  정신과개방일반병상수  290 non-null    int64
 28  격리병실병상수     290 non-null    int64
 29  무균치료실병상수    290 non-null    int64
dtypes: datetime64[ns](1), int64(20), object(9)
memory usage: 68.1+ KB

In [45]:
facility.isnull().sum()

암호화요양기호       0
요양기관명         0
종별코드          0
종별코드명         0
설립구분코드        0
설립구분코드명       0
시도코드          0
시도코드명         0
시군구코드         0
시군구코드명        0
읍면동           0
우편번호          0
주소            0
전화번호          0
개설일자          0
일반입원실상급병상수    0
일반입원실일반병상수    0
성인중환자병상수      0
소아중환자병상수      0
신생아중환자병상수     0
분만실병상수        0
수술실병상수        0
응급실병상수        0
물리치료실병상수      0
정신과폐쇄상급병상수    0
정신과폐쇄일반병상수    0
정신과개방상급병상수    0
정신과개방일반병상수    0
격리병실병상수       0
무균치료실병상수      0
dtype: int64

In [46]:
facility.duplicated().sum()

np.int64(0)

In [49]:
# 기초 통계
facility.select_dtypes(include="number").describe()

,종별코드,설립구분코드,시도코드,시군구코드,우편번호,일반입원실상급병상수,일반입원실일반병상수,성인중환자병상수,소아중환자병상수,신생아중환자병상수,분만실병상수,수술실병상수,응급실병상수,물리치료실병상수,정신과폐쇄상급병상수,정신과폐쇄일반병상수,정신과개방상급병상수,정신과개방일반병상수,격리병실병상수,무균치료실병상수
count,290.000000,290.000000,290.0,290.000000,290.000000,290.000000,290.000000,290.000000,290.000000,290.000000,290.000000,290.000000,290.000000,290.000000,290.000000,290.000000,290.000000,290.000000,290.000000,290.000000
mean,18.482759,10.762069,110000.0,110011.120690,5345.279310,12.186207,144.093103,8.086207,0.389655,2.189655,0.793103,4.865517,4.627586,12.644828,0.055172,1.527586,0.041379,0.603448,2.962069,0.820690
std,5.346931,2.743084,0.0,7.875497,2218.876413,30.215829,222.399641,24.423516,3.180264,8.449436,2.099255,8.417677,11.475230,13.351052,0.386257,6.561996,0.438239,3.106749,16.109335,4.293987
min,1.000000,1.000000,110000.0,110001.000000,1022.000000,0.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,21.000000,11.000000,110000.0,110003.000000,3375.000000,1.000000,42.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,4.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,21.000000,12.000000,110000.0,110011.000000,5706.500000,4.000000,69.500000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,21.000000,12.000000,110000.0,110018.000000,7291.250000,10.750000,144.500000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,16.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,21.000000,12.000000,110000.0,110025.000000,8864.000000,329.000000,1758.000000,189.000000,30.000000,62.000000,15.000000,76.000000,93.000000,128.000000,4.000000,60.000000,7.000000,21.000000,248.000000,46.000000

In [50]:
# 구별 병원 수
hospital["시군구코드명"].value_counts()

시군구코드명
강남구     36
송파구     24
강서구     24
강동구     20
영등포구    16
중랑구     16
동대문구    16
서초구     16
은평구     13
관악구     12
구로구     12
강북구     10
노원구      8
양천구      7
성북구      7
종로구      7
동작구      7
마포구      6
성동구      6
광진구      6
금천구      6
도봉구      5
서대문구     4
중구       4
용산구      2
Name: count, dtype: int64

**Dept. 진료_과목_정보**

In [51]:
dept.shape

(2740, 6)

In [53]:
dept.columns

Index(['암호화요양기호', '요양기관명', '진료과목코드', '진료과목코드명', '과목별 전문의수', '선택진료 의사수'], dtype='object')

In [54]:
dept.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2740 entries, 0 to 2739
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   암호화요양기호   2740 non-null   object
 1   요양기관명     2740 non-null   object
 2   진료과목코드    2740 non-null   int64
 3   진료과목코드명   2740 non-null   object
 4   과목별 전문의수  2740 non-null   int64
 5   선택진료 의사수  2740 non-null   int64
dtypes: int64(3), object(3)
memory usage: 128.6+ KB

In [56]:
dept.isnull().sum()

암호화요양기호     0
요양기관명       0
진료과목코드      0
진료과목코드명     0
과목별 전문의수    0
선택진료 의사수    0
dtype: int64

In [57]:
dept.duplicated().sum()

np.int64(0)

In [60]:
dept.groupby("진료과목코드명")["암호화요양기호"].nunique()

진료과목코드명
가정의학과           140
결핵과               4
구강내과             15
구강병리과             3
구강악안면외과          35
내과              250
마취통증의학과         203
방사선종양학과          32
병리과              51
비뇨의학과            75
사상체질과             8
산부인과             94
성형외과             61
소아청소년과          101
소아치과             10
신경과             118
신경외과            179
심장혈관흉부외과         44
안과               48
영상의학과           217
영상치의학과            5
예방의학과             2
예방치과              8
외과              125
응급의학과            57
이비인후과            58
재활의학과           133
정신건강의학과          54
정형외과            203
직업환경의학과          22
진단검사의학과          93
치과                2
치과교정과            24
치과보존과            26
치과보철과            31
치주과              24
침구과              17
통합치의학과           17
피부과              69
한방내과             20
한방부인과             6
한방소아과             4
한방신경정신과           5
한방안·이비인후·피부과      5
한방응급              1
한방재활의학과          13
핵의학과             28
Name: 암호화요양기호, dtype: int64

In [62]:
# 진료과목별 보유 병원 수
dept_6 = (
    dept[dept["진료과목코드명"].isin(target_depts)]
    .groupby("진료과목코드명")
    .agg(
        보유병원수=("암호화요양기호", "nunique"),
        전문의수합계=("과목별 전문의수", "sum"),
        평균전문의수=("과목별 전문의수", "mean")
    )
    .sort_values("보유병원수", ascending=False)
)

dept_6

         보유병원수  전문의수합계    평균전문의수
진료과목코드명
영상의학과      217    1107  5.101382
마취통증의학과    203     793  3.906404
정형외과       203     918  4.522167
신경외과       179     523  2.921788
재활의학과      133     268  2.015038
신경과        118     432  3.661017

**Traffic. 교통_정보**

In [64]:
traffic.shape

(369, 4)

In [65]:
traffic.columns

Index(['암호화요양기호', '교통편명', '노선번호', '교통편 코드'], dtype='object')

In [66]:
traffic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 369 entries, 0 to 368
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   암호화요양기호  369 non-null    object
 1   교통편명     369 non-null    object
 2   노선번호     362 non-null    object
 3   교통편 코드   369 non-null    int64
dtypes: int64(1), object(3)
memory usage: 11.7+ KB

In [67]:
traffic.isnull().sum()

암호화요양기호    0
교통편명       0
노선번호       7
교통편 코드     0
dtype: int64

In [68]:
traffic.duplicated().sum()

np.int64(11)

In [69]:
traffic[traffic.duplicated(keep=False)].sort_values("암호화요양기호")

                                               암호화요양기호  교통편명   노선번호  교통편 코드
216  JDQ4MTg4MSM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...   자가용    NaN       0
220  JDQ4MTg4MSM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...   자가용    NaN       0
219  JDQ4MTg4MSM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...   자가용    NaN       0
270  JDQ4MTg4MSM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...   지하철  4,7호선       5
269  JDQ4MTg4MSM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...   지하철  4,7호선       5
365  JDQ4MTg4MSM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...   지하철    5호선       5
366  JDQ4MTg4MSM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...   지하철    5호선       5
308  JDQ4MTg4MSM1MSMkMSMkMCMkOTkkMzgxMzUxIzMxIyQxIy...   지하철    7호선       5
309  JDQ4MTg4MSM1MSMkMSMkMCMkOTkkMzgxMzUxIzMxIyQxIy...   지하철    7호선       5
75   JDQ4MTg4MSM1MSMkMSMkMCMkOTkkMzgxMzUxIzMxIyQxIy...   자가용    NaN       0
74   JDQ4MTg4MSM1MSMkMSMkMCMkOTkkMzgxMzUxIzMxIyQxIy...   자가용    NaN       0
127  JDQ4MTg4MSM1MSMkMSMkMCMkOTkkMzgxMzUxIzMxIyQxIy...   지하철    2호선       5
128  JDQ4MTg4MSM1MSMkMSMkMCMkOTkkMzgxMzUxIzMxIyQxIy...   지하철    2호선       5
357  JDQ4MTg4MSM1MSMkMSMkMCMkOTkkMzgxMzUxIzMxIyQxIy...   지하철    5호선       5
358  JDQ4MTg4MSM1MSMkMSMkMCMkOTkkMzgxMzUxIzMxIyQxIy...   지하철    5호선       5
54   JDQ4MTg4MSM1MSMkMSMkMCMkOTkkMzgxMzUxIzQxIyQxIy...  시내버스    406       3
53   JDQ4MTg4MSM1MSMkMSMkMCMkOTkkMzgxMzUxIzQxIyQxIy...  시내버스    148       3
52   JDQ4MTg4MSM1MSMkMSMkMCMkOTkkMzgxMzUxIzQxIyQxIy...  시내버스    142       3
51   JDQ4MTg4MSM1MSMkMSMkMCMkOTkkMzgxMzUxIzQxIyQxIy...  시내버스    406       3
50   JDQ4MTg4MSM1MSMkMSMkMCMkOTkkMzgxMzUxIzQxIyQxIy...  시내버스    148       3
49   JDQ4MTg4MSM1MSMkMSMkMCMkOTkkMzgxMzUxIzQxIyQxIy...  시내버스    142       3

In [72]:
traffic_clean = traffic.drop_duplicates().copy()

traffic_clean.shape

(358, 4)

In [75]:
traffic_by_type = (
    traffic_clean
    .groupby(["암호화요양기호", "교통편명"])
    .size()
    .unstack(fill_value=0)
    .reset_index()
)

traffic_by_type.head()

교통편명,암호화요양기호,기차,마을버스,시내버스,시외/고속버스,자가용,지하철
0,JDQ4MTg4MSM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,0,0,6,0,0,0
1,JDQ4MTg4MSM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,0,0,0,0,0,1
2,JDQ4MTg4MSM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,0,0,3,0,0,3
3,JDQ4MTg4MSM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,0,0,3,0,0,2
4,JDQ4MTg4MSM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...,0,0,1,0,1,1

In [77]:
traffic_clean["암호화요양기호"].nunique()

65

In [78]:
traffic[traffic["노선번호"].isnull()]

                                               암호화요양기호  교통편명 노선번호  교통편 코드
74   JDQ4MTg4MSM1MSMkMSMkMCMkOTkkMzgxMzUxIzMxIyQxIy...   자가용  NaN       0
75   JDQ4MTg4MSM1MSMkMSMkMCMkOTkkMzgxMzUxIzMxIyQxIy...   자가용  NaN       0
216  JDQ4MTg4MSM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...   자가용  NaN       0
219  JDQ4MTg4MSM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...   자가용  NaN       0
220  JDQ4MTg4MSM1MSMkMSMkMCMkODkkMzgxMzUxIzExIyQxIy...   자가용  NaN       0
232  JDQ4MTg4MSM1MSMkMSMkMCMkOTkkMzgxMzUxIzExIyQxIy...   자가용  NaN       0
311  JDQ4MTg4MSM1MSMkMSMkMCMkOTkkMzgxMzUxIzMxIyQxIy...  시내버스  NaN       3